AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  refillQueue

  Sample SAM Template for refillQueue

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        ORIGINAL_QUEUE: dummy

Resources:
  ReDriveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
      Events:
        MyDLQEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:969902485569:nftTracker-MyDLQueue-hxEhWkdwSDox
            BatchSize: 10
