version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nftTracker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-192khg6z5d9ig"
s3_prefix = "nftTracker"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
